//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub email: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ssh_auth::Entity")]
    SshAuth,
}

impl Related<super::ssh_auth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SshAuth.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
