name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux binaries
    runs-on: ubuntu-latest
    steps:
      - name: "📄 Checkout"
        uses: actions/checkout@v4

      - name: "📦 Package linux x64"
        run: |
          cd "${{github.workspace}}"

          cargo build --release --bin cargo-work --bin horsed
          cd ./target/release

          zip -r work-${{runner.os}}-x64.zip cargo-work
          zip -r horsed-${{runner.os}}-x64.zip horsed

          gh release upload ${{github.event.release.tag_name}} work-${{runner.os}}-x64.zip
          gh release upload ${{github.event.release.tag_name}} horsed-${{runner.os}}-x64.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

  build-windows:
    name: Build Windows binaries
    runs-on: windows-latest
    steps:
      - name: "📄 Checkout"
        uses: actions/checkout@v4

      - name: "📦 Package windows x64"
        run: |
          cd "${{github.workspace}}"

          cargo build --release --bin cargo-work --bin horsed
          cd ./target/release

          7z a work-${{runner.os}}-x64.zip cargo-work.exe
          7z a horsed-${{runner.os}}-x64.zip horsed.exe

          gh release upload ${{github.event.release.tag_name}} work-${{runner.os}}-x64.zip
          gh release upload ${{github.event.release.tag_name}} horsed-${{runner.os}}-x64.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

  build-macos-arm:
    name: Build macOS arm binaries
    runs-on: macos-latest
    steps:
      - name: "📄 Checkout"
        uses: actions/checkout@v4

      - name: "📦 Package macos arm"
        run: |
          cd "${{github.workspace}}"

          cargo build --release --bin cargo-work --bin horsed
          cd ./target/release

          zip -r work-${{runner.os}}-arm.zip cargo-work
          zip -r horsed-${{runner.os}}-arm.zip horsed

          gh release upload ${{github.event.release.tag_name}} work-${{runner.os}}-arm.zip
          gh release upload ${{github.event.release.tag_name}} horsed-${{runner.os}}-arm.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
